### ISSUE TITLE
Cloudformation schema

### ISSUE THREAD

**Issue by elmobp** [allinwonder/cfnlego#3]
Hey,

With the release of the schema coming if you look at cfndsl there is the freestyle one there in the issues is it worth looking at porting this to the schema? Happy to help!

Would mean no code to update for each schema update

**Comment by elmobp** [comment]
Just a thought in the interim may write a tool t produce every resource and publish it as a zip to somewhere then hook this to add a option to refresh the resources. Given the way a resource is defined in here vs aws doco was very simple to translate between.

**Comment by allinwonder** [comment]
Merged into cfndsl tool! Great work @elmobp
